services:

# main app service
  app:
    container_name: bookstore-app
    build:
      context: .
      dockerfile: DockerFile
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

# db service
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: Bansal29
      MONGO_INITDB_ROOT_PASSWORD: Bansal@29

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: Bansal29
      ME_CONFIG_MONGODB_ADMINPASSWORD: Bansal@29
      ME_CONFIG_MONGODB_URL: mongodb+srv://Bansal29:Bansal%4029@cluster0.findv.mongodb.net/bookstore?retryWrites=true&w=majority
      ME_CONFIG_BASICAUTH: false
    volumes:
      - mongo-data:/data/db
volumes:
     mongo-data:

