# trying out running the mongodb atlas url through docker container and env variables
version: '3.8'

services:
  # Main app service
  app:
    container_name: bookstore-app
    build:
      context: .
      dockerfile: DockerFile
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      MONGODB_URL: "mmongodb+srv://Bansal29:Bansal%4029@cluster0.findv.mongodb.net/bookstore?retryWrites=true&w=majority"
  
# 