FROM node:22-alpine

# working directory inside the container
WORKDIR /app

# copy package.json and package-lock.json to the container
COPY package*.json ./

# install dependencies
RUN npm install

# copy the rest of the application code to the container
COPY . .

# expose port 3000 to the outside world
EXPOSE 3000

# start the application
CMD ["npm", "run", "start:dev"]